### ISSUE TITLE
Just some layers

### ISSUE THREAD

**Issue by Bunanai** [felt/qgis-plugin#29]
If I`m not in the wrong way, the plugin provides the upload to Felt platform off all layers of my Qgis open project. Is it possible to configure or select just the interested layers?

**Comment by samhashemi** [comment]
Not at the current moment, but we're thinking about only uploading the _checked_ layers in the next version of the plugin. Would that help?

![Uploading Screenshot 2023-06-28 at 7.10.38 PM.png…]()

**Comment by Bunanai** [comment]
Sure, exactly. It´s good to hear this. Indeed is not necessary to list all the advantages the users would have with this implementation. I´ll be waiting anxiously.

**Comment by doorgan** [comment]
Hi @Bunanai! We just launched a new plugin version!
As Sam mentioned earlier, now only the *checked* layers will be uploaded to your Felt map!
