### ISSUE TITLE
updating data

### ISSUE THREAD

**Issue by Bunanai** [felt/qgis-plugin#49]
Hi,
It is a wonderful tool for to who want to share a map on the web. Is it possible to update published data with new qgis export, in place of creating another dataset? It makes sense when you create a particular legend configuration (editing the source code)  and need to reuse it. See the export sequence: 

![image](https://github.com/felt/qgis-plugin/assets/29894272/0416f364-22fb-4240-97de-d105111723f8)

![image](https://github.com/felt/qgis-plugin/assets/29894272/2e453193-ca16-4d9f-87c8-cd2a495cbb42)

Thanks.

**Comment by doorgan** [comment]
Hi @Bunanai! Thank you for the feedback!

Updating a layer in this way is not currently supported, and for the time being we don't have plans to support it. Today Felt doesn't support changing the data source for a Layer; you can move the datasets from a layer around, but the datasets themselves can't be replaced.

We're definitely looking at ways to make the process more smooth though!

**Comment by Bunanai** [comment]
Ok, 
Maybe, as a suggestion, it could have an option to simply copy the configurations from one dataset to another, import or export to a json file, or something around this. 
Anyway, thanks for your kind and sincere reply.
