### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by martinRenou** [felt/qgis-plugin#89]
Thanks for this package!

Unless I'm mistaken, there is no license on the repository. Would you be able to add one?

**Comment by ChrisLoer** [comment]
Thanks for calling that to our attention -- I'll check and try to get a license posted here soon

**Comment by ChrisLoer** [comment]
OK, I just updated the license to GPLv2 to conform with the QGIS plugin requirements.

**Comment by martinRenou** [comment]
Thanks!
